package minesweeper;

public class Main {
    public static void main(String[] args) {
        System.out.println("""
                .X.......
                .....X..X
                ....X....
                ......X..
                ..X......
                ....X....
                ..X......
                ..X......
                ......X..""");
    }
}
